// GENERATED by scripts/extract-render-core.cjs from pi-markdown-preview 0.18.0 (26654f5).
// Do not edit by hand: change pi-markdown-preview and regenerate, so the two
// renderers stay identical until pi-markdown-preview depends on this package.
// @ts-nocheck is deliberately absent: this file is typechecked like the original.
import { basename, extname, join, resolve as resolvePath } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { readFileSync, statSync } from "node:fs";
import { getBrowserWatchLocalMediaPath } from "./shared/browser-watch-server.js";
import { readFile, stat } from "node:fs/promises";
import { BoundedProcessError, isSpawnNotFoundError, runBoundedProcess } from "./shared/bounded-process.js";
import { stripMarkdownHtmlCommentsPreservingYamlFrontMatter } from "./shared/markdown-html-comments.js";
import { normalizeSubSupTags } from "./shared/markdown-sub-sup.js";
import { hasMarkdownAnnotationMarkers, prepareMarkdownForPandocPreview } from "./shared/annotation-scanner.js";

/** Structural subset of Pi's Theme used by the renderer. Pi's Theme satisfies it. */
export interface PreviewTheme {
	readonly name?: string;
	readonly sourcePath?: string;
	getFgAnsi(color: any): string;
	getBgAnsi(color: any): string;
}
type Theme = PreviewTheme;

const PREVIEW_ANNOTATION_PLACEHOLDER_PREFIX = "PIMDPREVIEWANNOT";
const ANNOTATION_HELPERS_SOURCE = readFileSync(new URL("./client/annotation-helpers.js", import.meta.url), "utf-8");
const PDF_FIGURE_HELPERS_SOURCE = readFileSync(new URL("./client/pdf-figure-renderer.js", import.meta.url), "utf-8");
const CODE_WRAP_CONTROLS_SOURCE = readFileSync(new URL("./client/code-wrap-controls.js", import.meta.url), "utf-8");
const PANDOC_FIGURE_CROSSREF_FILTER_PATH = fileURLToPath(new URL("./shared/pandoc-figure-crossrefs.lua", import.meta.url));
const RENDER_VERSION = "v35";
const MERMAID_BROWSER_VERSION = "11.16.0";
const PDFJS_BROWSER_VERSION = "6.3.289";
const PDFJS_BROWSER_BASE_URL = `https://cdn.jsdelivr.net/npm/pdfjs-dist@${PDFJS_BROWSER_VERSION}/`;
const PDFJS_BROWSER_MODULE_URL = `${PDFJS_BROWSER_BASE_URL}build/pdf.min.mjs`;
const PDFJS_BROWSER_WORKER_URL = `${PDFJS_BROWSER_BASE_URL}build/pdf.worker.min.mjs`;
const PDFJS_BROWSER_DOCUMENT_OPTIONS = {
	cMapPacked: true,
	cMapUrl: `${PDFJS_BROWSER_BASE_URL}cmaps/`,
	iccUrl: `${PDFJS_BROWSER_BASE_URL}iccs/`,
	standardFontDataUrl: `${PDFJS_BROWSER_BASE_URL}standard_fonts/`,
	wasmUrl: `${PDFJS_BROWSER_BASE_URL}wasm/`,
};
const MERMAID_BROWSER_ICON_PACKS = [
	{ name: "lucide", url: "https://unpkg.com/@iconify-json/lucide@1/icons.json" },
	{ name: "logos", url: "https://unpkg.com/@iconify-json/logos@1/icons.json" },
] as const;
const DEFAULT_BROWSER_PREVIEW_FONT_SIZE_PX = 15;
const MIN_PREVIEW_FONT_SIZE_PX = 10;
const MAX_PREVIEW_FONT_SIZE_PX = 24;
const DEFAULT_PANDOC_RENDER_TIMEOUT_MS = 30000;
const MAX_RENDER_PROCESS_STDOUT_BYTES = 50 * 1024 * 1024;
const MAX_RENDER_PROCESS_STDERR_BYTES = 5 * 1024 * 1024;
const MAX_INLINE_BROWSER_PDF_BYTES = 16 * 1024 * 1024;
const MAX_INLINE_BROWSER_PDF_TOTAL_BASE64_BYTES = 32 * 1024 * 1024;

type ThemeMode = "dark" | "light";

interface PreviewPalette {
	bg: string;
	card: string;
	panel2: string;
	border: string;
	borderMuted: string;
	text: string;
	muted: string;
	accent: string;
	warn: string;
	error: string;
	ok: string;
	codeBg: string;
	link: string;
	mdHeading: string;
	mdLink: string;
	mdLinkUrl: string;
	mdCode: string;
	mdCodeBlock: string;
	mdCodeBlockBorder: string;
	mdQuote: string;
	mdQuoteBorder: string;
	mdHr: string;
	mdListBullet: string;
	syntaxComment: string;
	syntaxKeyword: string;
	syntaxFunction: string;
	syntaxVariable: string;
	syntaxString: string;
	syntaxNumber: string;
	syntaxType: string;
	syntaxOperator: string;
	syntaxPunctuation: string;
}

interface PreviewStyle {
	themeMode: ThemeMode;
	palette: PreviewPalette;
	cacheKey: string;
}

interface PreviewAnnotationPlaceholder {
	token: string;
	text: string;
	title: string;
}

interface PreparedFilePreview {
	markdown: string;
	isLatex: boolean;
}

const DARK_PREVIEW_PALETTE: PreviewPalette = {
	bg: "#0f1117",
	card: "#171b24",
	panel2: "#11161f",
	border: "#2d3748",
	borderMuted: "#242b38",
	text: "#e6edf3",
	muted: "#9aa5b1",
	accent: "#5ea1ff",
	warn: "#f9c74f",
	error: "#ff6b6b",
	ok: "#73d13d",
	codeBg: "#11161f",
	link: "#81a2be",
	mdHeading: "#f0c674",
	mdLink: "#81a2be",
	mdLinkUrl: "#666666",
	mdCode: "#8abeb7",
	mdCodeBlock: "#b5bd68",
	mdCodeBlockBorder: "#808080",
	mdQuote: "#808080",
	mdQuoteBorder: "#808080",
	mdHr: "#808080",
	mdListBullet: "#8abeb7",
	syntaxComment: "#6A9955",
	syntaxKeyword: "#569CD6",
	syntaxFunction: "#DCDCAA",
	syntaxVariable: "#9CDCFE",
	syntaxString: "#CE9178",
	syntaxNumber: "#B5CEA8",
	syntaxType: "#4EC9B0",
	syntaxOperator: "#D4D4D4",
	syntaxPunctuation: "#D4D4D4",
};

const LIGHT_PREVIEW_PALETTE: PreviewPalette = {
	bg: "#f5f7fb",
	card: "#ffffff",
	panel2: "#f8fafc",
	border: "#d0d7de",
	borderMuted: "#e0e6ee",
	text: "#1f2328",
	muted: "#57606a",
	accent: "#0969da",
	warn: "#9a6700",
	error: "#cf222e",
	ok: "#1a7f37",
	codeBg: "#f8fafc",
	link: "#547da7",
	mdHeading: "#9a7326",
	mdLink: "#547da7",
	mdLinkUrl: "#767676",
	mdCode: "#5a8080",
	mdCodeBlock: "#588458",
	mdCodeBlockBorder: "#6c6c6c",
	mdQuote: "#6c6c6c",
	mdQuoteBorder: "#6c6c6c",
	mdHr: "#6c6c6c",
	mdListBullet: "#588458",
	syntaxComment: "#008000",
	syntaxKeyword: "#0000FF",
	syntaxFunction: "#795E26",
	syntaxVariable: "#001080",
	syntaxString: "#A31515",
	syntaxNumber: "#098658",
	syntaxType: "#267F99",
	syntaxOperator: "#000000",
	syntaxPunctuation: "#000000",
};

function inferThemeModeFromName(name: string): ThemeMode | undefined {
	const lower = name.toLowerCase();
	if (/\b(light|dawn|day|latte)\b/.test(lower) || lower.includes("-light")) return "light";
	if (/\b(dark|night|moon|mocha)\b/.test(lower) || lower.includes("-dark")) return "dark";
	return undefined;
}

function normalizePreviewFontSizePx(fontSizePx?: number, defaultFontSizePx = DEFAULT_BROWSER_PREVIEW_FONT_SIZE_PX): number {
	if (!Number.isFinite(fontSizePx)) return defaultFontSizePx;
	const clamped = Math.max(MIN_PREVIEW_FONT_SIZE_PX, Math.min(MAX_PREVIEW_FONT_SIZE_PX, Number(fontSizePx)));
	return Math.round(clamped * 10) / 10;
}

function needsWindowsCommandShell(command: string): boolean {
	return process.platform === "win32" && /\.(?:bat|cmd)$/i.test(command.trim());
}

async function runPandocProcess(
	args: string[],
	input: string,
	options: { label: string; timeoutMs: number; signal?: AbortSignal },
): Promise<{ code: number | null; signal: NodeJS.Signals | null; stderr: Buffer; stdout: Buffer }> {
	const pandocCommand = process.env.PANDOC_PATH?.trim() || "pandoc";
	try {
		return await runBoundedProcess(pandocCommand, args, {
			input,
			label: options.label,
			maxStderrBytes: MAX_RENDER_PROCESS_STDERR_BYTES,
			maxStdoutBytes: MAX_RENDER_PROCESS_STDOUT_BYTES,
			windowsCmdShim: needsWindowsCommandShell(pandocCommand),
			signal: options.signal,
			timeoutMs: options.timeoutMs,
		});
	} catch (error) {
		if (isSpawnNotFoundError(error)) {
			throw new Error("pandoc was not found. Install pandoc or set PANDOC_PATH to the pandoc binary.", { cause: error });
		}
		if (error instanceof BoundedProcessError && error.kind === "aborted") {
			throw new Error("Preview rendering cancelled.", { cause: error });
		}
		throw error;
	}
}

function formatProcessExit(code: number | null, signal: NodeJS.Signals | null): string {
	return code === null ? `signal ${signal ?? "unknown"}` : `exit code ${code}`;
}

function throwIfPreviewCancelled(signal?: AbortSignal): void {
	if (signal?.aborted) throw new Error("Preview rendering cancelled.");
}

function toHexByte(value: number): string {
	const clamped = Math.max(0, Math.min(255, Math.round(value)));
	return clamped.toString(16).padStart(2, "0");
}

function rgbToHex(r: number, g: number, b: number): string {
	return `#${toHexByte(r)}${toHexByte(g)}${toHexByte(b)}`;
}

function hexToRgb(color: string): { r: number; g: number; b: number } | undefined {
	const value = color.trim();
	const long = value.match(/^#([0-9a-fA-F]{6})$/);
	if (long) {
		const hex = long[1]!;
		return {
			r: Number.parseInt(hex.slice(0, 2), 16),
			g: Number.parseInt(hex.slice(2, 4), 16),
			b: Number.parseInt(hex.slice(4, 6), 16),
		};
	}

	const short = value.match(/^#([0-9a-fA-F]{3})$/);
	if (short) {
		const hex = short[1]!;
		return {
			r: Number.parseInt(hex[0]! + hex[0]!, 16),
			g: Number.parseInt(hex[1]! + hex[1]!, 16),
			b: Number.parseInt(hex[2]! + hex[2]!, 16),
		};
	}

	return undefined;
}

function xterm256ToHex(index: number): string {
	const basic16 = [
		"#000000",
		"#800000",
		"#008000",
		"#808000",
		"#000080",
		"#800080",
		"#008080",
		"#c0c0c0",
		"#808080",
		"#ff0000",
		"#00ff00",
		"#ffff00",
		"#0000ff",
		"#ff00ff",
		"#00ffff",
		"#ffffff",
	];

	if (index >= 0 && index < basic16.length) {
		return basic16[index]!;
	}

	if (index >= 16 && index <= 231) {
		const i = index - 16;
		const r = Math.floor(i / 36);
		const g = Math.floor((i % 36) / 6);
		const b = i % 6;
		const values = [0, 95, 135, 175, 215, 255];
		return rgbToHex(values[r]!, values[g]!, values[b]!);
	}

	if (index >= 232 && index <= 255) {
		const gray = 8 + (index - 232) * 10;
		return rgbToHex(gray, gray, gray);
	}

	return "#000000";
}

function ansiColorToCss(ansi: string): string | undefined {
	const trueColorMatch = ansi.match(/\x1b\[(?:38|48);2;(\d{1,3});(\d{1,3});(\d{1,3})m/);
	if (trueColorMatch) {
		return rgbToHex(Number(trueColorMatch[1]), Number(trueColorMatch[2]), Number(trueColorMatch[3]));
	}

	const indexedMatch = ansi.match(/\x1b\[(?:38|48);5;(\d{1,3})m/);
	if (indexedMatch) {
		return xterm256ToHex(Number(indexedMatch[1]));
	}

	return undefined;
}

function safeThemeColor(getter: () => string): string | undefined {
	try {
		return ansiColorToCss(getter());
	} catch {
		return undefined;
	}
}

function withAlpha(color: string, alpha: number, fallback: string): string {
	const rgb = hexToRgb(color);
	if (!rgb) return fallback;
	const clamped = Math.max(0, Math.min(1, alpha));
	return `rgba(${rgb.r}, ${rgb.g}, ${rgb.b}, ${clamped.toFixed(2)})`;
}

function adjustBrightness(color: string, factor: number): string {
	const rgb = hexToRgb(color);
	if (!rgb) return color;
	return rgbToHex(
		Math.round(rgb.r * factor),
		Math.round(rgb.g * factor),
		Math.round(rgb.b * factor),
	);
}

function relativeLuminance(color: string): number {
	const rgb = hexToRgb(color);
	if (!rgb) return 0;
	return (0.299 * rgb.r + 0.587 * rgb.g + 0.114 * rgb.b) / 255;
}

function blendColors(a: string, b: string, t: number): string {
	const rgbA = hexToRgb(a);
	const rgbB = hexToRgb(b);
	if (!rgbA || !rgbB) return a;
	return rgbToHex(
		Math.round(rgbA.r + (rgbB.r - rgbA.r) * t),
		Math.round(rgbA.g + (rgbB.g - rgbA.g) * t),
		Math.round(rgbA.b + (rgbB.b - rgbA.b) * t),
	);
}

function wcagRelativeLuminance(color: string): number {
	const rgb = hexToRgb(color);
	if (!rgb) return 0;
	const linear = [rgb.r, rgb.g, rgb.b].map((channel) => {
		const value = channel / 255;
		return value <= 0.03928 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4;
	});
	return 0.2126 * linear[0]! + 0.7152 * linear[1]! + 0.0722 * linear[2]!;
}

function contrastRatio(a: string, b: string): number {
	const lumA = wcagRelativeLuminance(a);
	const lumB = wcagRelativeLuminance(b);
	const lighter = Math.max(lumA, lumB);
	const darker = Math.min(lumA, lumB);
	return (lighter + 0.05) / (darker + 0.05);
}

function capBorderContrast(color: string, surface: string, maxContrast: number): string {
	if (!hexToRgb(color) || !hexToRgb(surface)) return color;
	if (contrastRatio(color, surface) <= maxContrast) return color;

	let low = 0;
	let high = 1;
	let result = color;
	for (let i = 0; i < 12; i += 1) {
		const mid = (low + high) / 2;
		const candidate = blendColors(color, surface, mid);
		if (contrastRatio(candidate, surface) > maxContrast) {
			low = mid;
		} else {
			result = candidate;
			high = mid;
		}
	}
	return result;
}

function deriveCanvasColors(
	baseColor: string,
	themeMode: ThemeMode,
): { pageBg: string; cardBg: string; panel2: string } {
	if (themeMode === "dark") {
		const pageBg = adjustBrightness(baseColor, 0.50);
		const cardBg = adjustBrightness(baseColor, 0.60);
		return {
			pageBg,
			cardBg,
			panel2: adjustBrightness(baseColor, 0.72),
		};
	}
	const lum = relativeLuminance(baseColor);
	const lighten = (c: string, amount: number): string => {
		const rgb = hexToRgb(c);
		if (!rgb) return c;
		return rgbToHex(
			Math.round(rgb.r + (255 - rgb.r) * amount),
			Math.round(rgb.g + (255 - rgb.g) * amount),
			Math.round(rgb.b + (255 - rgb.b) * amount),
		);
	};
	if (lum > 0.92) {
		return { pageBg: baseColor, cardBg: "#ffffff", panel2: lighten(baseColor, 0.3) };
	}
	return {
		pageBg: lighten(baseColor, 0.6),
		cardBg: lighten(baseColor, 0.93),
		panel2: lighten(baseColor, 0.45),
	};
}

function adjustCodeBg(cardHex: string, themeMode: ThemeMode): string {
	const rgb = hexToRgb(cardHex);
	if (!rgb) return cardHex;
	if (themeMode === "dark") {
		const f = 0.85;
		return rgbToHex(Math.round(rgb.r * f), Math.round(rgb.g * f), Math.round(rgb.b * f));
	}
	const f = 0.97;
	return rgbToHex(Math.round(rgb.r * f), Math.round(rgb.g * f), Math.round(rgb.b * f));
}

interface ThemeExportPalette {
	pageBg?: string;
	cardBg?: string;
	infoBg?: string;
}

interface ThemeSourceJson {
	name?: string;
	vars?: Record<string, string | number>;
	colors?: Record<string, string | number>;
	export?: { pageBg?: string | number; cardBg?: string | number; infoBg?: string | number };
}

const themeSourceJsonCache = new Map<string, { mtimeMs: number; json: ThemeSourceJson | null }>();

function resolveThemeExportValue(
	value: string | number | undefined,
	vars: Record<string, string | number>,
	seen: Set<string> = new Set(),
): string | undefined {
	if (value == null) return undefined;
	if (typeof value === "number") return xterm256ToHex(value);

	const token = value.trim();
	if (!token) return undefined;
	if (token.startsWith("#")) return token;

	const varKey = token.startsWith("$") ? token.slice(1) : token;
	if (!varKey || seen.has(varKey)) return token;

	const referenced = vars[varKey];
	if (referenced == null) return token;

	seen.add(varKey);
	return resolveThemeExportValue(referenced, vars, seen) ?? token;
}

function isCssColorValue(value: string | undefined): value is string {
	if (!value) return false;
	const trimmed = value.trim();
	return /^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.test(trimmed) || /^rgba?\(/i.test(trimmed);
}

function normalizeResolvedThemeColor(value: string | undefined): string | undefined {
	if (!isCssColorValue(value)) return undefined;
	return value.trim();
}

function readThemeSourceJson(theme?: Theme): ThemeSourceJson | undefined {
	const sourcePath = theme?.sourcePath?.trim();
	if (!sourcePath) return undefined;

	try {
		const mtimeMs = statSync(sourcePath).mtimeMs;
		const cached = themeSourceJsonCache.get(sourcePath);
		if (cached && cached.mtimeMs === mtimeMs) return cached.json ?? undefined;

		const raw = readFileSync(sourcePath, "utf-8");
		const parsed = JSON.parse(raw) as ThemeSourceJson;
		themeSourceJsonCache.set(sourcePath, { mtimeMs, json: parsed });
		return parsed;
	} catch {
		themeSourceJsonCache.set(sourcePath, { mtimeMs: -1, json: null });
		return undefined;
	}
}

function resolveThemeJsonValue(
	value: string | number | undefined,
	vars: Record<string, string | number>,
): string | undefined {
	return normalizeResolvedThemeColor(resolveThemeExportValue(value, vars));
}

function readThemeExportPalette(theme?: Theme): ThemeExportPalette | undefined {
	const parsed = readThemeSourceJson(theme);
	if (!parsed) return undefined;
	const vars = parsed.vars ?? {};
	const exportSection = parsed.export ?? {};
	const resolved: ThemeExportPalette = {
		pageBg: resolveThemeJsonValue(exportSection.pageBg, vars),
		cardBg: resolveThemeJsonValue(exportSection.cardBg, vars),
		infoBg: resolveThemeJsonValue(exportSection.infoBg, vars),
	};
	return resolved.pageBg || resolved.cardBg || resolved.infoBg ? resolved : undefined;
}

function readThemeColorToken(theme: Theme | undefined, token: string): string | undefined {
	const parsed = readThemeSourceJson(theme);
	if (!parsed) return undefined;
	return resolveThemeJsonValue(parsed.colors?.[token], parsed.vars ?? {});
}

function readThemeVarColor(theme: Theme | undefined, keys: string[]): string | undefined {
	const parsed = readThemeSourceJson(theme);
	if (!parsed) return undefined;
	const vars = parsed.vars ?? {};
	for (const key of keys) {
		const color = resolveThemeJsonValue(vars[key], vars);
		if (color) return color;
	}
	return undefined;
}

function readThemeAnyColor(theme: Theme | undefined, keys: string[]): string | undefined {
	const parsed = readThemeSourceJson(theme);
	if (!parsed) return undefined;
	const vars = parsed.vars ?? {};
	for (const key of keys) {
		const color = resolveThemeJsonValue(parsed.colors?.[key], vars);
		if (color) return color;
	}
	return undefined;
}

function inferThemeModeFromColor(color: string | undefined): ThemeMode | undefined {
	if (!color || !hexToRgb(color)) return undefined;
	return relativeLuminance(color) >= 0.58 ? "light" : "dark";
}

function inferThemeModeFromColorCandidates(...colors: Array<string | undefined>): ThemeMode | undefined {
	for (const color of colors) {
		const inferred = inferThemeModeFromColor(color);
		if (inferred) return inferred;
	}
	return undefined;
}

function getThemeMode(theme?: Theme): ThemeMode {
	const exported = readThemeExportPalette(theme);
	const inferredFromExport = inferThemeModeFromColorCandidates(exported?.pageBg, exported?.cardBg);
	if (inferredFromExport) return inferredFromExport;

	const inferredFromSurface = inferThemeModeFromColorCandidates(
		inferThemeSurfaceColor(theme, "page"),
		inferThemeSurfaceColor(theme, "card"),
		readThemeColorToken(theme, "userMessageBg"),
		readThemeColorToken(theme, "customMessageBg"),
		readThemeColorToken(theme, "toolPendingBg"),
	);
	if (inferredFromSurface) return inferredFromSurface;

	const inferredFromName = inferThemeModeFromName(theme?.name ?? "");
	if (inferredFromName) return inferredFromName;

	return "dark";
}

function inferThemeTextColor(theme: Theme | undefined, themeMode: ThemeMode): string | undefined {
	return readThemeAnyColor(theme, ["text", "userMessageText", "customMessageText", "mdCodeBlock"])
		?? readThemeVarColor(
			theme,
			themeMode === "light"
				? ["text", "fg", "foreground", "textDark1", "fg0", "fg1", "nord0"]
				: ["text", "fg", "foreground", "fg0", "fg1", "subtext1", "subtext0", "nord4", "gray3"],
		);
}

function inferThemeSurfaceColor(theme: Theme | undefined, role: "page" | "card" | "panel2"): string | undefined {
	if (role === "page") {
		return readThemeVarColor(theme, ["pageBg", "bg", "base", "background", "mantle", "bg_dark", "bg0", "nord0"]);
	}
	if (role === "card") {
		return readThemeVarColor(theme, ["cardBg", "surface", "base", "bg", "bg1", "nord1"]);
	}
	return readThemeVarColor(theme, ["infoBg", "surfaceAlt", "surface0", "overlay", "bg_hl", "bg2", "nord2"]);
}

function getPreviewStyle(theme?: Theme): PreviewStyle {
	const themeMode = getThemeMode(theme);
	const fallback = themeMode === "dark" ? DARK_PREVIEW_PALETTE : LIGHT_PREVIEW_PALETTE;

	if (!theme) {
		return {
			themeMode,
			palette: fallback,
			cacheKey: [themeMode, ...Object.values(fallback)].join("|"),
		};
	}

	const exported = readThemeExportPalette(theme);
	const accent =
		safeThemeColor(() => theme.getFgAnsi("mdLink"))
		?? safeThemeColor(() => theme.getFgAnsi("accent"))
		?? readThemeColorToken(theme, "mdLink")
		?? readThemeColorToken(theme, "accent")
		?? fallback.accent;
	const warn = safeThemeColor(() => theme.getFgAnsi("warning")) ?? readThemeColorToken(theme, "warning") ?? fallback.warn;
	const error = safeThemeColor(() => theme.getFgAnsi("error")) ?? readThemeColorToken(theme, "error") ?? fallback.error;
	const ok = safeThemeColor(() => theme.getFgAnsi("success")) ?? readThemeColorToken(theme, "success") ?? fallback.ok;
	const text = safeThemeColor(() => theme.getFgAnsi("text")) ?? inferThemeTextColor(theme, themeMode) ?? fallback.text;

	const surfaceBase =
		safeThemeColor(() => theme.getBgAnsi("userMessageBg"))
		?? safeThemeColor(() => theme.getBgAnsi("customMessageBg"))
		?? readThemeColorToken(theme, "userMessageBg")
		?? readThemeColorToken(theme, "customMessageBg");
	const derived = surfaceBase ? deriveCanvasColors(surfaceBase, themeMode) : undefined;
	const themePageBg = inferThemeSurfaceColor(theme, "page");
	const themeCardBg = inferThemeSurfaceColor(theme, "card");
	const themePanel2 = inferThemeSurfaceColor(theme, "panel2");

	const card =
		exported?.cardBg
		?? themeCardBg
		?? derived?.cardBg
		?? safeThemeColor(() => theme.getBgAnsi("toolPendingBg"))
		?? readThemeColorToken(theme, "toolPendingBg")
		?? fallback.card;
	const panel2 =
		themePanel2
		?? derived?.panel2
		?? safeThemeColor(() => theme.getBgAnsi("selectedBg"))
		?? readThemeColorToken(theme, "selectedBg")
		?? exported?.infoBg
		?? adjustCodeBg(card, themeMode)
		?? fallback.panel2;
	const mdLink = safeThemeColor(() => theme.getFgAnsi("mdLink")) ?? readThemeColorToken(theme, "mdLink") ?? accent;

	const palette: PreviewPalette = {
		bg:
			exported?.pageBg
			?? themePageBg
			?? derived?.pageBg
			?? fallback.bg,
		card,
		panel2,
		border: safeThemeColor(() => theme.getFgAnsi("border")) ?? readThemeColorToken(theme, "border") ?? fallback.border,
		borderMuted: safeThemeColor(() => theme.getFgAnsi("borderMuted")) ?? readThemeColorToken(theme, "borderMuted") ?? fallback.borderMuted,
		text,
		muted: safeThemeColor(() => theme.getFgAnsi("muted")) ?? readThemeColorToken(theme, "muted") ?? fallback.muted,
		accent,
		warn,
		error,
		ok,
		codeBg: panel2,
		link: mdLink,
		mdHeading: safeThemeColor(() => theme.getFgAnsi("mdHeading")) ?? readThemeColorToken(theme, "mdHeading") ?? fallback.mdHeading,
		mdLink,
		mdLinkUrl: safeThemeColor(() => theme.getFgAnsi("mdLinkUrl")) ?? readThemeColorToken(theme, "mdLinkUrl") ?? fallback.mdLinkUrl,
		mdCode: safeThemeColor(() => theme.getFgAnsi("mdCode")) ?? readThemeColorToken(theme, "mdCode") ?? fallback.mdCode,
		mdCodeBlock: safeThemeColor(() => theme.getFgAnsi("mdCodeBlock")) ?? readThemeColorToken(theme, "mdCodeBlock") ?? text,
		mdCodeBlockBorder: safeThemeColor(() => theme.getFgAnsi("mdCodeBlockBorder")) ?? readThemeColorToken(theme, "mdCodeBlockBorder") ?? fallback.mdCodeBlockBorder,
		mdQuote: safeThemeColor(() => theme.getFgAnsi("mdQuote")) ?? readThemeColorToken(theme, "mdQuote") ?? fallback.mdQuote,
		mdQuoteBorder: safeThemeColor(() => theme.getFgAnsi("mdQuoteBorder")) ?? readThemeColorToken(theme, "mdQuoteBorder") ?? fallback.mdQuoteBorder,
		mdHr: safeThemeColor(() => theme.getFgAnsi("mdHr")) ?? readThemeColorToken(theme, "mdHr") ?? fallback.mdHr,
		mdListBullet: safeThemeColor(() => theme.getFgAnsi("mdListBullet")) ?? readThemeColorToken(theme, "mdListBullet") ?? fallback.mdListBullet,
		syntaxComment: safeThemeColor(() => theme.getFgAnsi("syntaxComment")) ?? readThemeColorToken(theme, "syntaxComment") ?? fallback.syntaxComment,
		syntaxKeyword: safeThemeColor(() => theme.getFgAnsi("syntaxKeyword")) ?? readThemeColorToken(theme, "syntaxKeyword") ?? fallback.syntaxKeyword,
		syntaxFunction: safeThemeColor(() => theme.getFgAnsi("syntaxFunction")) ?? readThemeColorToken(theme, "syntaxFunction") ?? fallback.syntaxFunction,
		syntaxVariable: safeThemeColor(() => theme.getFgAnsi("syntaxVariable")) ?? readThemeColorToken(theme, "syntaxVariable") ?? fallback.syntaxVariable,
		syntaxString: safeThemeColor(() => theme.getFgAnsi("syntaxString")) ?? readThemeColorToken(theme, "syntaxString") ?? fallback.syntaxString,
		syntaxNumber: safeThemeColor(() => theme.getFgAnsi("syntaxNumber")) ?? readThemeColorToken(theme, "syntaxNumber") ?? fallback.syntaxNumber,
		syntaxType: safeThemeColor(() => theme.getFgAnsi("syntaxType")) ?? readThemeColorToken(theme, "syntaxType") ?? fallback.syntaxType,
		syntaxOperator: safeThemeColor(() => theme.getFgAnsi("syntaxOperator")) ?? readThemeColorToken(theme, "syntaxOperator") ?? fallback.syntaxOperator,
		syntaxPunctuation: safeThemeColor(() => theme.getFgAnsi("syntaxPunctuation")) ?? readThemeColorToken(theme, "syntaxPunctuation") ?? fallback.syntaxPunctuation,
	};

	return {
		themeMode,
		palette,
		cacheKey: [themeMode, ...Object.values(palette)].join("|"),
	};
}

function extractAssistantMarkdownContent(content: unknown): string | undefined {
	if (!Array.isArray(content)) return undefined;
	const textBlocks = content.filter((block): block is { type: "text"; text: string } => {
		if (!block || typeof block !== "object" || !("type" in block) || block.type !== "text" || !("text" in block)) return false;
		return typeof block.text === "string" && !!block.text.trim();
	});
	return textBlocks.length > 0 ? textBlocks.map((block) => block.text).join("\n\n") : undefined;
}

function prepareFilePreview(filePath: string, fileContent: string): PreparedFilePreview {
	if (isLatexFile(filePath)) return { markdown: fileContent, isLatex: true };
	if (isMarkdownFile(filePath)) return { markdown: fileContent, isLatex: false };
	return {
		markdown: wrapCodeAsMarkdown(fileContent, detectLanguageFromPath(filePath), filePath),
		isLatex: false,
	};
}

function isLikelyMathExpression(expr: string): boolean {
	const content = expr.trim();
	if (content.length === 0) return false;

	if (/\\[a-zA-Z]+/.test(content)) return true; // LaTeX commands like \frac, \alpha
	if (/[0-9]/.test(content)) return true;
	if (/[=+\-*/^_<>≤≥±×÷]/u.test(content)) return true;
	if (/[{}]/.test(content)) return true;
	if (/[α-ωΑ-Ω]/u.test(content)) return true;
	if (/^[A-Za-z]$/.test(content)) return true; // single-variable forms like \(x\)

	// Plain words (e.g. escaped markdown like \[not a link\]) are not math.
	if (/^[A-Za-z][A-Za-z\s'".,:;!?-]*[A-Za-z]$/.test(content)) return false;

	return false;
}

function normalizeMathDelimitersInSegment(markdown: string): string {
	let normalized = markdown.replace(/\\\[\s*([\s\S]*?)\s*\\\]/g, (match, expr: string) => {
		const content = expr.trim();
		if (!isLikelyMathExpression(content)) return match;
		return content.length > 0 ? `$$\n${content}\n$$` : "$$\n$$";
	});

	normalized = normalized.replace(/\\\(([\s\S]*?)\\\)/g, (match, expr: string) => {
		if (!isLikelyMathExpression(expr)) return match;
		return `$${expr}$`;
	});
	return normalized;
}

function normalizeMathDelimiters(markdown: string): string {
	const lines = markdown.split("\n");
	const out: string[] = [];
	let plainBuffer: string[] = [];
	let inFence = false;
	let fenceChar: "`" | "~" | undefined;
	let fenceLength = 0;

	const flushPlain = () => {
		if (plainBuffer.length === 0) return;
		out.push(normalizeMathDelimitersInSegment(plainBuffer.join("\n")));
		plainBuffer = [];
	};

	for (const line of lines) {
		const trimmed = line.trimStart();
		const fenceMatch = trimmed.match(/^(`{3,}|~{3,})/);

		if (fenceMatch) {
			const marker = fenceMatch[1]!;
			const markerChar = marker[0] as "`" | "~";
			const markerLength = marker.length;

			if (!inFence) {
				flushPlain();
				inFence = true;
				fenceChar = markerChar;
				fenceLength = markerLength;
				out.push(line);
				continue;
			}

			if (fenceChar === markerChar && markerLength >= fenceLength) {
				inFence = false;
				fenceChar = undefined;
				fenceLength = 0;
			}

			out.push(line);
			continue;
		}

		if (inFence) {
			out.push(line);
		} else {
			plainBuffer.push(line);
		}
	}

	flushPlain();
	return out.join("\n");
}

function formatMarkdownImageDestination(rawPath: string): string {
	const path = rawPath.trim();
	if (!path) return "";
	const unwrapped = path.startsWith("<") && path.endsWith(">") ? path.slice(1, -1).trim() : path;
	// Angle brackets keep markdown image destinations valid for spaces/parentheses.
	if (/[\s<>()]/.test(unwrapped)) return `<${unwrapped}>`;
	return unwrapped;
}

function normalizeObsidianImages(markdown: string): string {
	// Convert ![[path|alt]] and ![[path]] to standard markdown ![alt](path)
	return markdown
		.replace(/!\[\[([^|\]]+)\|([^\]]+)\]\]/g, (_match, path: string, alt: string) => {
			return `![${alt}](${formatMarkdownImageDestination(path)})`;
		})
		.replace(/!\[\[([^\]]+)\]\]/g, (_match, path: string) => {
			return `![](${formatMarkdownImageDestination(path)})`;
		});
}

const MARKDOWN_EXTENSIONS = new Set(["md", "markdown", "mdx", "rmd", "qmd"]);

const EXT_TO_LANG: Record<string, string> = {
	ts: "typescript", tsx: "typescript", mts: "typescript", cts: "typescript",
	js: "javascript", jsx: "javascript", mjs: "javascript", cjs: "javascript",
	py: "python", pyw: "python",
	rb: "ruby",
	rs: "rust",
	go: "go",
	java: "java",
	kt: "kotlin", kts: "kotlin",
	swift: "swift",
	c: "c", h: "c",
	cpp: "cpp", cxx: "cpp", cc: "cpp", hpp: "cpp", hxx: "cpp",
	cs: "csharp",
	php: "php",
	sh: "bash", bash: "bash", zsh: "bash",
	fish: "fish",
	ps1: "powershell",
	sql: "sql",
	html: "html", htm: "html",
	css: "css", scss: "scss", sass: "sass", less: "less",
	json: "json", jsonc: "json", json5: "json",
	yaml: "yaml", yml: "yaml",
	toml: "toml",
	xml: "xml",
	dockerfile: "dockerfile",
	makefile: "makefile",
	cmake: "cmake",
	lua: "lua",
	perl: "perl", pl: "perl",
	r: "r",
	jl: "julia",
	scala: "scala",
	clj: "clojure",
	ex: "elixir", exs: "elixir",
	erl: "erlang",
	hs: "haskell",
	ml: "ocaml",
	vim: "vim",
	graphql: "graphql",
	proto: "protobuf",
	tf: "hcl", hcl: "hcl",
	tex: "latex", latex: "latex",
	qmd: "markdown",
	diff: "diff", patch: "diff",
	f90: "fortran", f95: "fortran", f03: "fortran", f: "fortran", for: "fortran",
	m: "matlab",
};

function detectLanguageFromPath(filePath: string): string | undefined {
	const ext = extname(filePath).replace(/^\./, "").toLowerCase();
	if (ext) return EXT_TO_LANG[ext];

	const baseLower = basename(filePath).toLowerCase();
	if (baseLower === "dockerfile") return "dockerfile";
	if (baseLower === "makefile") return "makefile";
	return undefined;
}

function isMarkdownFile(filePath: string): boolean {
	const ext = extname(filePath).replace(/^\./, "").toLowerCase();
	return MARKDOWN_EXTENSIONS.has(ext);
}

const LATEX_EXTENSIONS = new Set(["tex", "latex"]);

function isLatexFile(filePath: string): boolean {
	const ext = extname(filePath).replace(/^\./, "").toLowerCase();
	return LATEX_EXTENSIONS.has(ext);
}

function normalizeFenceLanguage(language: string | undefined): string | undefined {
	const trimmed = typeof language === "string" ? language.trim().toLowerCase() : "";
	if (!trimmed) return undefined;
	if (trimmed === "patch" || trimmed === "udiff") return "diff";
	return trimmed;
}

function getLongestFenceRun(text: string, fenceChar: "`" | "~"): number {
	const regex = fenceChar === "`" ? /`+/g : /~+/g;
	let max = 0;
	let match: RegExpExecArray | null;
	while ((match = regex.exec(text)) !== null) {
		max = Math.max(max, match[0].length);
	}
	return max;
}

function wrapCodeAsMarkdown(code: string, lang?: string, filePath?: string): string {
	const header = filePath ? `# ${basename(filePath)}\n\n` : "";
	const source = String(code ?? "").replace(/\r\n/g, "\n").trimEnd();
	const language = normalizeFenceLanguage(lang) ?? "";
	const maxBackticks = getLongestFenceRun(source, "`");
	const maxTildes = getLongestFenceRun(source, "~");

	let markerChar: "`" | "~" = "`";
	if (maxBackticks === 0 && maxTildes === 0) {
		markerChar = "`";
	} else if (maxTildes < maxBackticks) {
		markerChar = "~";
	} else if (maxBackticks < maxTildes) {
		markerChar = "`";
	} else {
		markerChar = maxBackticks > 0 ? "~" : "`";
	}

	const markerLength = Math.max(3, (markerChar === "`" ? maxBackticks : maxTildes) + 1);
	const marker = markerChar.repeat(markerLength);
	return `${header}${marker}${language}\n${source}\n${marker}`;
}

function normalizeMarkdownFencedBlocks(markdown: string): string {
	const lines = String(markdown ?? "").replace(/\r\n/g, "\n").split("\n");
	const out: string[] = [];

	for (let index = 0; index < lines.length; index += 1) {
		const line = lines[index] ?? "";
		const openingMatch = line.match(/^(\s{0,3})(`{3,}|~{3,})([^\n]*)$/);
		if (!openingMatch) {
			out.push(line);
			continue;
		}

		const indent = openingMatch[1] ?? "";
		const openingFence = openingMatch[2]!;
		const openingSuffix = openingMatch[3] ?? "";
		const fenceChar = openingFence[0] as "`" | "~";
		const fenceLength = openingFence.length;

		let closingIndex = -1;
		for (let innerIndex = index + 1; innerIndex < lines.length; innerIndex += 1) {
			const innerLine = lines[innerIndex] ?? "";
			const closingMatch = innerLine.match(/^\s{0,3}(`{3,}|~{3,})\s*$/);
			if (!closingMatch) continue;
			const closingFence = closingMatch[1]!;
			if (closingFence[0] !== fenceChar || closingFence.length < fenceLength) continue;
			closingIndex = innerIndex;
			break;
		}

		if (closingIndex === -1) {
			out.push(line);
			continue;
		}

		const contentLines = lines.slice(index + 1, closingIndex);
		const content = contentLines.join("\n");
		const maxBackticks = getLongestFenceRun(content, "`");
		const maxTildes = getLongestFenceRun(content, "~");
		const currentMaxRun = fenceChar === "`" ? maxBackticks : maxTildes;

		if (currentMaxRun < fenceLength) {
			out.push(line, ...contentLines, lines[closingIndex] ?? "");
			index = closingIndex;
			continue;
		}

		const neededBackticks = Math.max(3, maxBackticks + 1);
		const neededTildes = Math.max(3, maxTildes + 1);
		let markerChar: "`" | "~" = fenceChar;

		if (neededBackticks < neededTildes) {
			markerChar = "`";
		} else if (neededTildes < neededBackticks) {
			markerChar = "~";
		} else if (fenceChar === "`") {
			markerChar = "~";
		}

		const markerLength = markerChar === "`" ? neededBackticks : neededTildes;
		const marker = markerChar.repeat(markerLength);
		out.push(`${indent}${marker}${openingSuffix}`, ...contentLines, `${indent}${marker}`);
		index = closingIndex;
	}

	return out.join("\n");
}

function prepareBrowserPreviewMarkdown(markdown: string, isLatex?: boolean): {
	normalizedMarkdown: string;
	pandocMarkdown: string;
	annotationPlaceholders: PreviewAnnotationPlaceholder[];
} {
	const markdownWithoutHtmlComments = isLatex ? markdown : stripMarkdownHtmlCommentsPreservingYamlFrontMatter(markdown);
	const normalizedMarkdown = isLatex ? markdownWithoutHtmlComments : normalizeSubSupTags(normalizeMarkdownFencedBlocks(normalizeObsidianImages(normalizeMathDelimiters(markdownWithoutHtmlComments))));
	if (isLatex || !hasMarkdownAnnotationMarkers(normalizedMarkdown)) {
		return { normalizedMarkdown, pandocMarkdown: normalizedMarkdown, annotationPlaceholders: [] };
	}

	const prepared = prepareMarkdownForPandocPreview(normalizedMarkdown, PREVIEW_ANNOTATION_PLACEHOLDER_PREFIX) as {
		markdown?: string;
		placeholders?: PreviewAnnotationPlaceholder[];
	};
	return {
		normalizedMarkdown,
		pandocMarkdown: typeof prepared.markdown === "string" ? prepared.markdown : normalizedMarkdown,
		annotationPlaceholders: Array.isArray(prepared.placeholders) ? prepared.placeholders : [],
	};
}

async function renderMarkdownToHtmlWithPandoc(
	markdown: string,
	resourcePath?: string,
	isLatex?: boolean,
	signal?: AbortSignal,
): Promise<string> {
	const pandocInput = isLatex ? markdown : normalizeMarkdownFencedBlocks(markdown);
	const inputFormat = isLatex ? "latex" : "markdown+lists_without_preceding_blankline-blank_before_blockquote-blank_before_header+tex_math_dollars+autolink_bare_uris-raw_html-raw_attribute";
	const args = ["-f", inputFormat, "-t", "html5", "--mathml", "--wrap=none"];
	if (!isLatex) args.push(`--lua-filter=${PANDOC_FIGURE_CROSSREF_FILTER_PATH}`);
	if (resourcePath) args.push(`--resource-path=${resourcePath}`);

	const result = await runPandocProcess(args, pandocInput, {
		label: "pandoc HTML render",
		signal,
		timeoutMs: DEFAULT_PANDOC_RENDER_TIMEOUT_MS,
	});
	if (result.code === 0) return result.stdout.toString("utf-8");
	const stderr = result.stderr.toString("utf-8").trim();
	throw new Error(`pandoc failed with ${formatProcessExit(result.code, result.signal)}${stderr ? `: ${stderr}` : ""}`);
}

function buildPreviewCssVars(style: PreviewStyle, fontSizePx?: number): Record<string, string> {
	const palette = style.palette;
	const previewFontSizePx = normalizePreviewFontSizePx(fontSizePx);
	const rawBorderSubtle = blendColors(palette.borderMuted, palette.card, style.themeMode === "light" ? 0.58 : 0.48);
	const rawPanelBorder = blendColors(palette.borderMuted, palette.card, style.themeMode === "light" ? 0.42 : 0.36);
	const borderSubtle = capBorderContrast(rawBorderSubtle, palette.card, style.themeMode === "light" ? 1.10 : 1.12);
	const panelBorder = capBorderContrast(rawPanelBorder, palette.card, style.themeMode === "light" ? 1.15 : 1.18);
	const blockquoteBg = withAlpha(
		palette.mdQuoteBorder,
		style.themeMode === "light" ? 0.10 : 0.16,
		style.themeMode === "light" ? "rgba(15, 23, 42, 0.04)" : "rgba(255, 255, 255, 0.05)",
	);
	const tableAltBg = withAlpha(
		palette.mdCodeBlockBorder,
		style.themeMode === "light" ? 0.10 : 0.14,
		style.themeMode === "light" ? "rgba(15, 23, 42, 0.03)" : "rgba(255, 255, 255, 0.04)",
	);
	const inlineCodeBg = withAlpha(
		palette.mdCodeBlockBorder,
		style.themeMode === "light" ? 0.13 : 0.18,
		style.themeMode === "light" ? "rgba(15, 23, 42, 0.06)" : "rgba(255, 255, 255, 0.07)",
	);
	const rawCodeBlockBorder = blendColors(palette.mdCodeBlockBorder, palette.panel2, style.themeMode === "light" ? 0.62 : 0.72);
	const codeBlockBorder = capBorderContrast(rawCodeBlockBorder, palette.panel2, style.themeMode === "light" ? 1.16 : 1.18);
	const diffAddedBg = withAlpha(palette.ok, style.themeMode === "light" ? 0.10 : 0.14, "rgba(46, 160, 67, 0.12)");
	const diffRemovedBg = withAlpha(palette.error, style.themeMode === "light" ? 0.10 : 0.14, "rgba(248, 81, 73, 0.12)");

	return {
		"color-scheme": style.themeMode,
		"--preview-font-size": `${previewFontSizePx}px`,
		"--bg": palette.bg,
		"--card": palette.card,
		"--panel-2": palette.panel2,
		"--border": palette.border,
		"--border-muted": palette.borderMuted,
		"--border-subtle": borderSubtle,
		"--panel-border": panelBorder,
		"--text": palette.text,
		"--muted": palette.muted,
		"--accent": palette.accent,
		"--warn": palette.warn,
		"--error": palette.error,
		"--ok": palette.ok,
		"--code-bg": palette.codeBg,
		"--link": palette.link,
		"--md-heading": palette.mdHeading,
		"--md-link": palette.mdLink,
		"--md-link-url": palette.mdLinkUrl,
		"--md-code": palette.mdCode,
		"--md-codeblock": palette.mdCodeBlock,
		"--md-codeblock-border": codeBlockBorder,
		"--md-quote": palette.mdQuote,
		"--md-quote-border": palette.mdQuoteBorder,
		"--md-hr": palette.mdHr,
		"--md-list-bullet": palette.mdListBullet,
		"--syntax-keyword": palette.syntaxKeyword,
		"--syntax-function": palette.syntaxFunction,
		"--syntax-variable": palette.syntaxVariable,
		"--syntax-string": palette.syntaxString,
		"--syntax-number": palette.syntaxNumber,
		"--syntax-type": palette.syntaxType,
		"--syntax-comment": palette.syntaxComment,
		"--syntax-operator": palette.syntaxOperator,
		"--syntax-punctuation": palette.syntaxPunctuation,
		"--syntax-error": palette.error,
		"--annotation-bg": withAlpha(palette.accent, style.themeMode === "light" ? 0.13 : 0.25, style.themeMode === "light" ? "rgba(9, 105, 218, 0.14)" : "rgba(88, 166, 255, 0.22)"),
		"--annotation-border": withAlpha(palette.accent, style.themeMode === "light" ? 0.45 : 0.65, style.themeMode === "light" ? "rgba(9, 105, 218, 0.40)" : "rgba(88, 166, 255, 0.62)"),
		"--annotation-text": palette.text,
		"--blockquote-bg": blockquoteBg,
		"--inline-code-bg": inlineCodeBg,
		"--table-alt-bg": tableAltBg,
		"--md-table-border": borderSubtle,
		"--diff-add-bg": diffAddedBg,
		"--diff-add-text": palette.ok,
		"--diff-del-bg": diffRemovedBg,
		"--diff-del-text": palette.error,
		"--diff-meta-text": palette.muted,
		"--diff-header-bg": withAlpha(palette.accent, style.themeMode === "light" ? 0.08 : 0.10, style.themeMode === "light" ? "rgba(9, 105, 218, 0.08)" : "rgba(88, 166, 255, 0.10)"),
		"--diff-header-text": palette.accent,
		"--diff-hunk-bg": withAlpha(palette.accent, style.themeMode === "light" ? 0.12 : 0.16, style.themeMode === "light" ? "rgba(9, 105, 218, 0.12)" : "rgba(88, 166, 255, 0.16)"),
		"--diff-hunk-text": palette.accent,
	};
}

export function buildMermaidBrowserModule(mermaidConfigJson: string, mermaidIconPacksJson: string): string {
	return String.raw`
    const setMermaidRenderResult = (status, error) => {
      window.__mermaidRenderResult = error ? { status, error } : { status };
    };
    const renderMermaidFailure = (wrappers, message) => {
      wrappers.forEach((wrapper) => {
        const failure = document.createElement('pre');
        failure.className = 'mermaid-error';
        failure.setAttribute('role', 'alert');
        failure.style.cssText = 'margin:0;padding:12px 14px;border:1px solid var(--error,#cf222e);border-radius:8px;background:var(--panel-2,#f8fafc);color:var(--error,#cf222e);text-align:left;white-space:pre-wrap;overflow-wrap:anywhere;';
        failure.textContent = 'Mermaid render failed: ' + message;
        wrapper.replaceChildren(failure);
      });
    };
    const renderMermaid = async () => {
      const mermaidBlocks = document.querySelectorAll('pre.mermaid');
      if (mermaidBlocks.length === 0) {
        setMermaidRenderResult('skipped');
        return;
      }

      setMermaidRenderResult('pending');
      const wrappers = Array.from(mermaidBlocks).map((pre) => {
        const code = pre.querySelector('code');
        const src = code ? code.textContent : pre.textContent;
        const wrapper = document.createElement('div');
        wrapper.className = 'mermaid-container';
        const div = document.createElement('div');
        div.className = 'mermaid';
        div.textContent = src;
        wrapper.appendChild(div);
        pre.replaceWith(wrapper);
        return wrapper;
      });

      try {
        const { default: mermaid } = await import('https://cdn.jsdelivr.net/npm/mermaid@${MERMAID_BROWSER_VERSION}/dist/mermaid.esm.min.mjs');
        const packs = ${mermaidIconPacksJson};
        const pending = new Map();
        let iconPackError = null;
        const load = (pack) => {
          if (!pending.has(pack.name)) {
            pending.set(pack.name, fetch(pack.url).then((response) => {
              if (!response.ok) throw new Error('Failed to load Mermaid icon pack ' + pack.name + ': HTTP ' + response.status);
              return response.json();
            }).catch((error) => {
              iconPackError ??= error instanceof Error ? error : new Error(String(error));
              throw error;
            }));
          }
          return pending.get(pack.name);
        };
        mermaid.registerIconPacks(packs.map((pack) => ({ name: pack.name, loader: () => load(pack) })));
        mermaid.initialize(${mermaidConfigJson});
        await mermaid.run();
        if (iconPackError) throw iconPackError;
        const parseRgb = (value) => {
          const match = value.match(/^rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)/);
          return match ? [Number(match[1]), Number(match[2]), Number(match[3])] : null;
        };
        const isOpaqueColor = (value) => {
          if (!parseRgb(value)) return false;
          const alphaMatch = value.match(/^rgba\(\s*[\d.]+\s*,\s*[\d.]+\s*,\s*[\d.]+\s*,\s*([\d.]+)\s*\)$/);
          return !alphaMatch || Number(alphaMatch[1]) >= 1;
        };
        const findOpaqueFill = (root) => {
          if (!(root instanceof Element)) return null;
          const shape = Array.from(root.querySelectorAll('rect, polygon, path, circle, ellipse')).find((candidate) => {
            const fill = getComputedStyle(candidate).fill;
            return isOpaqueColor(fill);
          });
          return shape ? getComputedStyle(shape).fill : null;
        };
        const findOpaqueBackground = (element, fallback) => {
          let current = element instanceof Element ? element : null;
          while (current) {
            const background = getComputedStyle(current).backgroundColor;
            if (current instanceof HTMLElement && isOpaqueColor(background)) return background;
            current = current.parentElement;
          }
          return fallback;
        };
        const relativeLuminance = (color) => {
          const linear = color.map((channel) => {
            const value = channel / 255;
            return value <= 0.04045 ? value / 12.92 : Math.pow((value + 0.055) / 1.055, 2.4);
          });
          return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2];
        };
        const contrastRatio = (foreground, background) => {
          const lighter = Math.max(relativeLuminance(foreground), relativeLuminance(background));
          const darker = Math.min(relativeLuminance(foreground), relativeLuminance(background));
          return (lighter + 0.05) / (darker + 0.05);
        };
        const toRgb = (color) => 'rgb(' + color.map((channel) => Math.round(channel)).join(', ') + ')';
        const ensureReadableColor = (foregroundCss, backgroundCss) => {
          const foreground = parseRgb(foregroundCss);
          const background = parseRgb(backgroundCss);
          if (!foreground || !background || contrastRatio(foreground, background) >= 4.5) return foregroundCss;
          const readableCandidates = [[0, 0, 0], [255, 255, 255]].flatMap((target) => {
            for (let step = 1; step <= 20; step += 1) {
              const amount = step / 20;
              const color = foreground.map((channel, index) => channel + (target[index] - channel) * amount);
              if (contrastRatio(color, background) >= 4.5) return [{ amount, color }];
            }
            return [];
          });
          readableCandidates.sort((left, right) => left.amount - right.amount);
          if (readableCandidates.length > 0) return toRgb(readableCandidates[0].color);
          const black = [0, 0, 0];
          const white = [255, 255, 255];
          return toRgb(contrastRatio(black, background) >= contrastRatio(white, background) ? black : white);
        };
        const pageBackground = getComputedStyle(document.body).backgroundColor;
        document.querySelectorAll('.mermaid-container .icon-shape').forEach((node) => {
          const icon = node.querySelector('svg');
          if (!icon) return;
          const semanticColor = getComputedStyle(icon).color;
          const iconSurface = findOpaqueFill(node.firstElementChild)
            || findOpaqueBackground(icon, pageBackground);
          const iconColor = ensureReadableColor(semanticColor, iconSurface);
          icon.style.setProperty('color', iconColor, 'important');
          node.querySelectorAll('.labelBkg, .nodeLabel').forEach((label) => {
            if (!(label instanceof HTMLElement)) return;
            const labelSurface = findOpaqueBackground(label, pageBackground);
            const labelColor = ensureReadableColor(semanticColor, labelSurface);
            label.style.setProperty('color', labelColor, 'important');
          });
        });
        document.querySelectorAll('.mermaid-container .node:not(.icon-shape)').forEach((node) => {
          const shape = Array.from(node.querySelectorAll('rect, polygon, path, circle, ellipse')).find((candidate) => {
            const fill = getComputedStyle(candidate).fill;
            return fill && fill !== 'none' && fill !== 'rgba(0, 0, 0, 0)';
          });
          if (!shape) return;
          const shapeFill = getComputedStyle(shape).fill;
          node.querySelectorAll('.nodeLabel').forEach((label) => {
            if (!(label instanceof HTMLElement)) return;
            const labelColor = ensureReadableColor(getComputedStyle(label).color, shapeFill);
            label.style.setProperty('color', labelColor, 'important');
          });
        });
        setMermaidRenderResult('success');
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        setMermaidRenderResult('failed', message);
        renderMermaidFailure(wrappers, message);
        console.error('Mermaid render failed:', error);
      }
    };
  `;
}

function decodeHtmlMediaSourceAttribute(value: string): string {
	return value.replace(/&(amp|quot|apos|#39|#x27|#\d+|#x[\da-f]+);/gi, (entity, name: string) => {
		switch (name.toLowerCase()) {
			case "amp": return "&";
			case "quot": return '"';
			case "apos":
			case "#39":
			case "#x27": return "'";
			default: {
				const numeric = name.startsWith("#x")
					? Number.parseInt(name.slice(2), 16)
					: Number.parseInt(name.slice(1), 10);
				return Number.isSafeInteger(numeric) && numeric >= 0 && numeric <= 0x10ffff
					? String.fromCodePoint(numeric)
					: entity;
			}
		}
	});
}

function isPdfEmbedSource(source: string): boolean {
	const decoded = decodeHtmlMediaSourceAttribute(source.trim());
	let pathPart = decoded.split(/[?#]/, 1)[0];
	try {
		pathPart = decodeURIComponent(pathPart);
	} catch {
		return false;
	}
	if (/^[\\/]{2}/.test(pathPart)) return false;
	const scheme = /^([a-zA-Z][a-zA-Z\d+.-]*):/.exec(pathPart)?.[1]?.toLowerCase();
	if (scheme && !["http", "https", "file", "data", "blob"].includes(scheme) && !/^[a-zA-Z]:[\\/]/.test(pathPart)) return false;
	if (scheme === "data") return /^data:application\/pdf(?:[;,])/i.test(pathPart);
	return extname(pathPart).toLowerCase() === ".pdf";
}

function markPandocPdfEmbeds(fragmentHtml: string): string {
	let pdfIndex = 0;
	return fragmentHtml.replace(/<embed\b[^>]*>/gi, (tag) => {
		const canonicalTag = tag.replace(
			/\sdata-pi-markdown-preview-pdf(?:-index)?(?:\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+))?/gi,
			"",
		);
		const sourceMatch = canonicalTag.match(/\ssrc\s*=\s*(["'])([^"']*)\1/i);
		if (!sourceMatch || !isPdfEmbedSource(sourceMatch[2] ?? "")) return canonicalTag;
		const index = String(pdfIndex++);
		return canonicalTag.replace(
			/^<embed\b/i,
			`<embed data-pi-markdown-preview-pdf="true" data-pi-markdown-preview-pdf-index="${index}"`,
		);
	});
}

async function collectInlineLocalPdfData(
	fragmentHtml: string,
	resourcePath: string | undefined,
	signal?: AbortSignal,
): Promise<Record<string, string>> {
	const sources: Array<{ index: string; source: string }> = [];
	for (const match of fragmentHtml.matchAll(/<embed\b[^>]*\sdata-pi-markdown-preview-pdf\s*=\s*["']true["'][^>]*>/gi)) {
		const sourceMatch = match[0].match(/\ssrc\s*=\s*(["'])([^"']*)\1/i);
		const indexMatch = match[0].match(/\sdata-pi-markdown-preview-pdf-index\s*=\s*(["'])([^"']*)\1/i);
		if (sourceMatch && indexMatch) {
			sources.push({ index: indexMatch[2] ?? "", source: decodeHtmlMediaSourceAttribute(sourceMatch[2] ?? "") });
		}
	}
	if (sources.length === 0) return {};

	const rootPath = resolvePath(resourcePath ?? process.cwd());
	const cachedData = new Map<string, string | null>();
	const inlineData: Record<string, string> = {};
	let totalBase64Bytes = 0;
	for (const { index, source } of sources) {
		throwIfPreviewCancelled(signal);
		const localPath = getBrowserWatchLocalMediaPath(source, rootPath);
		if (!localPath || extname(localPath).toLowerCase() !== ".pdf") {
			continue;
		}
		if (cachedData.has(localPath)) {
			const cached = cachedData.get(localPath) ?? null;
			if (cached && totalBase64Bytes + cached.length <= MAX_INLINE_BROWSER_PDF_TOTAL_BASE64_BYTES) {
				totalBase64Bytes += cached.length;
				inlineData[index] = cached;
			}
			continue;
		}

		let encoded: string | null = null;
		try {
			const metadata = await stat(localPath);
			const estimatedBase64Bytes = Math.ceil(metadata.size / 3) * 4;
			if (metadata.isFile()
				&& metadata.size <= MAX_INLINE_BROWSER_PDF_BYTES
				&& totalBase64Bytes + estimatedBase64Bytes <= MAX_INLINE_BROWSER_PDF_TOTAL_BASE64_BYTES) {
				const bytes = await readFile(localPath, { signal });
				if (bytes.length <= MAX_INLINE_BROWSER_PDF_BYTES) {
					const candidate = bytes.toString("base64");
					if (totalBase64Bytes + candidate.length <= MAX_INLINE_BROWSER_PDF_TOTAL_BASE64_BYTES) {
						encoded = candidate;
						totalBase64Bytes += candidate.length;
					}
				}
			}
		} catch {
			throwIfPreviewCancelled(signal);
		}
		cachedData.set(localPath, encoded);
		if (encoded) inlineData[index] = encoded;
	}
	return inlineData;
}

function buildBrowserHtmlFromPandocFragment(
	fragmentHtml: string,
	style: PreviewStyle,
	resourcePath?: string,
	annotationPlaceholders: PreviewAnnotationPlaceholder[] = [],
	fontSizePx?: number,
	inlinePdfData: Record<string, string> = {},
	pdfFigureRenderingEnabled = false,
	codeWrapping: { wrapCode?: boolean; controls?: boolean } = {},
): string {
	const palette = style.palette;
	const preparedFragmentHtml = markPandocPdfEmbeds(fragmentHtml);
	const cssVarsBlock = Object.entries(buildPreviewCssVars(style, fontSizePx)).map(([key, value]) => `  ${key}: ${value};`).join("\n");
	const mermaidConfig = {
		startOnLoad: false,
		theme: "base",
		themeVariables: {
			background: palette.bg,
			primaryColor: palette.panel2,
			primaryTextColor: palette.text,
			primaryBorderColor: palette.mdCodeBlockBorder,
			secondaryColor: palette.card,
			secondaryTextColor: palette.text,
			secondaryBorderColor: palette.mdCodeBlockBorder,
			tertiaryColor: palette.card,
			tertiaryTextColor: palette.text,
			tertiaryBorderColor: palette.mdCodeBlockBorder,
			lineColor: palette.mdQuote,
			textColor: palette.text,
			edgeLabelBackground: palette.panel2,
			nodeBorder: palette.mdCodeBlockBorder,
			clusterBkg: palette.card,
			clusterBorder: palette.mdCodeBlockBorder,
			titleColor: palette.mdHeading,
		},
	};
	const mermaidConfigJson = JSON.stringify(mermaidConfig).replace(/</g, "\\u003c");
	const mermaidIconPacksJson = JSON.stringify(MERMAID_BROWSER_ICON_PACKS).replace(/</g, "\\u003c");
	const baseTag = resourcePath ? `\n<base href="${pathToFileURL(resourcePath + "/").href}" />` : "";
	const annotationHelpersScript = ANNOTATION_HELPERS_SOURCE.replace(/<\/script/gi, "<\\/script");
	const pdfFigureHelpersScript = PDF_FIGURE_HELPERS_SOURCE.replace(/<\/script/gi, "<\\/script");
	const codeWrapControlsScript = CODE_WRAP_CONTROLS_SOURCE.replace(/<\/script/gi, "<\\/script");
	const annotationPlaceholdersJson = JSON.stringify(annotationPlaceholders).replace(/</g, "\\u003c");
	const inlinePdfDataJson = JSON.stringify(inlinePdfData).replace(/</g, "\\u003c");
	return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />${baseTag}
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>Markdown Preview</title>
<style>
:root {
${cssVarsBlock}
}
* { box-sizing: border-box; }
html, body {
  margin: 0;
  padding: 0;
  background: var(--bg);
  color: var(--text);
}
body {
  min-height: 100vh;
  padding: 28px;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
}
#preview-root {
  width: min(1100px, 100%);
  margin: 0 auto;
  background: var(--card);
  border: 1px solid var(--panel-border);
  border-radius: 10px;
  padding: 24px 28px;
  overflow-wrap: anywhere;
  line-height: 1.58;
  font-size: var(--preview-font-size);
}
#preview-root h1, #preview-root h2, #preview-root h3, #preview-root h4, #preview-root h5, #preview-root h6 {
  margin-top: 1.2em;
  margin-bottom: 0.5em;
  line-height: 1.25;
  letter-spacing: -0.01em;
  color: var(--md-heading);
}
#preview-root h1 { font-size: 1.6em; border-bottom: 0; padding-bottom: 0; }
#preview-root h2 { font-size: 1.25em; border-bottom: 0; padding-bottom: 0; }
#preview-root p, #preview-root ul, #preview-root ol, #preview-root blockquote, #preview-root table {
  margin-top: 0;
  margin-bottom: 1em;
}
#preview-root li::marker { color: var(--md-list-bullet); }
#preview-root a { color: var(--md-link); text-decoration: none; }
#preview-root a:hover { text-decoration: underline; }
#preview-root a.uri, #preview-root .uri { color: var(--md-link-url); }
#preview-root blockquote {
  margin-left: 0;
  padding: 0.2em 1em;
  border-left: 0.25em solid var(--md-quote-border);
  border-radius: 0 8px 8px 0;
  background: var(--blockquote-bg);
  color: var(--md-quote);
}
#preview-root pre {
  background: var(--panel-2);
  border: 1px solid var(--md-codeblock-border);
  border-radius: 8px;
  padding: 12px 14px;
  overflow: auto;
  white-space: pre;
  overflow-wrap: normal;
}
#preview-root[data-wrap-code="true"] pre,
#preview-root pre[data-wrap-code="true"] {
  white-space: pre-wrap;
  overflow-wrap: anywhere;
}
#preview-root pre[data-wrap-code="false"] {
  white-space: pre;
  overflow-wrap: normal;
}
#preview-root .preview-code-toolbar,
#preview-root .preview-code-block-controls {
  display: flex;
  justify-content: flex-end;
  user-select: none;
}
#preview-root .preview-code-toolbar { margin-bottom: 0.3em; }
#preview-root .preview-code-block { position: relative; margin: max(12px, 0.85em) 0; min-width: 0; }
#preview-root .preview-code-block > pre { margin: 0; }
/* Straddle the border: no control row, and the lower half fits in the code padding. */
#preview-root .preview-code-block-controls {
  position: absolute;
  top: 0;
  right: 4px;
  gap: 2px;
  transform: translateY(-50%);
  z-index: 1;
  opacity: 0;
  pointer-events: none;
}
/* Pointer-acquired focus must not keep a button visible after mouseleave. */
#preview-root .preview-code-block:hover > .preview-code-block-controls,
#preview-root .preview-code-block-controls:has(> button:focus-visible) {
  opacity: 1;
  pointer-events: auto;
}
@media (hover: none), (any-pointer: coarse) {
  #preview-root .preview-code-block-controls { opacity: 1; pointer-events: auto; }
}
#preview-root .preview-code-toolbar button,
#preview-root .preview-code-block-controls button {
  background: transparent;
  border: 1px solid transparent;
  border-radius: 4px;
  color: var(--muted);
  cursor: pointer;
  font: 500 12px/1.3 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  min-height: 24px;
  padding: 2px 6px;
}
#preview-root .preview-code-block-controls button {
  background: var(--card);
  border-color: var(--border-muted);
  height: 24px;
  padding-inline: 3px;
  white-space: nowrap;
}
#preview-root [data-code-copy-block] { flex: 0 0 52px; width: 52px; }
#preview-root [data-code-copy-block][aria-busy="true"] { cursor: progress; }
#preview-root .preview-code-copy-status,
.preview-code-copy-buffer {
  position: fixed;
  top: 0;
  left: 0;
  width: 1px;
  height: 1px;
  overflow: hidden;
  clip-path: inset(50%);
  white-space: pre;
  pointer-events: none;
}
#preview-root .preview-code-toolbar button:hover,
#preview-root .preview-code-toolbar button:focus-visible,
#preview-root .preview-code-block-controls button:hover,
#preview-root .preview-code-block-controls button:focus-visible {
  background: var(--panel-2);
  border-color: var(--border-muted);
  color: var(--text);
}
#preview-root .preview-code-toolbar button:focus-visible,
#preview-root .preview-code-block-controls button:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }
/* Keep even the focus ring inside the badge, away from the first code line. */
#preview-root .preview-code-block-controls button:focus-visible { outline-offset: -2px; }
@media print {
  #preview-root .preview-code-toolbar,
  #preview-root .preview-code-block-controls,
  .preview-code-copy-buffer { display: none; }
}
#preview-root code {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
  font-size: 0.9em;
  color: var(--md-code);
}
#preview-root pre code {
  color: var(--text);
}
#preview-root :not(pre) > code {
  background: var(--inline-code-bg);
  border: 1px solid var(--md-codeblock-border);
  border-radius: 6px;
  padding: 0.12em 0.35em;
}
#preview-root .annotation-marker {
  display: inline;
  border-radius: 4px;
  border: 1px solid var(--annotation-border);
  background: var(--annotation-bg);
  color: var(--annotation-text);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
  padding: 0 0.28em;
}
#preview-root .annotation-marker mjx-container {
  margin: 0;
}
#preview-root pre.sourceCode.diff code > .diff-line {
  display: block;
  margin: 0 -4px;
  padding: 0 4px;
  border-radius: 4px;
}
#preview-root pre.sourceCode.diff code > .diff-add-line {
  background: var(--diff-add-bg);
  color: var(--diff-add-text);
}
#preview-root pre.sourceCode.diff code > .diff-del-line {
  background: var(--diff-del-bg);
  color: var(--diff-del-text);
}
#preview-root pre.sourceCode.diff code > .diff-meta-line {
  color: var(--diff-meta-text);
}
#preview-root pre.sourceCode.diff code > .diff-header-line {
  background: var(--diff-header-bg);
  color: var(--diff-header-text);
  font-weight: 600;
}
#preview-root pre.sourceCode.diff code > .diff-hunk-line {
  background: var(--diff-hunk-bg);
  color: var(--diff-hunk-text);
}
#preview-root pre.sourceCode.diff code > .diff-line .kw,
#preview-root pre.sourceCode.diff code > .diff-line .dt,
#preview-root pre.sourceCode.diff code > .diff-line .st,
#preview-root pre.sourceCode.diff code > .diff-line .va {
  color: inherit;
  font-weight: inherit;
}
#preview-root code span.kw,
#preview-root code span.cf,
#preview-root code span.im {
  color: var(--syntax-keyword);
  font-weight: 600;
}
#preview-root code span.dt {
  color: var(--syntax-type);
  font-weight: 600;
}
#preview-root code span.fu,
#preview-root code span.bu {
  color: var(--syntax-function);
}
#preview-root code span.va,
#preview-root code span.ot {
  color: var(--syntax-variable);
}
#preview-root code span.st,
#preview-root code span.ss,
#preview-root code span.sc,
#preview-root code span.ch {
  color: var(--syntax-string);
}
#preview-root code span.dv,
#preview-root code span.bn,
#preview-root code span.fl {
  color: var(--syntax-number);
}
#preview-root code span.co {
  color: var(--syntax-comment);
  font-style: italic;
}
#preview-root code span.op {
  color: var(--syntax-operator);
}
#preview-root code span.pp,
#preview-root code span.pu {
  color: var(--syntax-punctuation);
}
#preview-root code span.er,
#preview-root code span.al {
  color: var(--syntax-error);
  font-weight: 600;
}
#preview-root table {
  border-collapse: collapse;
  display: block;
  max-width: 100%;
  overflow: auto;
}
#preview-root th, #preview-root td {
  border: 1px solid var(--md-table-border);
  padding: 6px 12px;
}
#preview-root thead th {
  background: var(--panel-2);
}
#preview-root tbody tr:nth-child(even) {
  background: var(--table-alt-bg);
}
#preview-root hr {
  border: 0;
  border-top: 1px solid var(--md-hr);
  margin: 1.25em 0;
}
#preview-root img { max-width: 100%; }
#preview-root embed {
  display: block;
  width: 100%;
  max-width: 100%;
  height: 360px;
  margin: 0 auto;
}
#preview-root .pdf-page-preview {
  display: block;
  max-width: 100%;
  margin: 0 auto;
  position: relative;
  text-decoration: none;
}
#preview-root .pdf-page-preview:hover { text-decoration: none; }
#preview-root .pdf-page-preview-canvas {
  background: #fff;
  border: 1px solid var(--border-subtle);
  border-radius: 4px;
  display: block;
  max-width: 100%;
}
#preview-root .pdf-page-preview:focus-visible .pdf-page-preview-canvas,
#preview-root a:focus-visible > .pdf-page-preview .pdf-page-preview-canvas,
#preview-root .pdf-page-preview:hover .pdf-page-preview-canvas {
  outline: 2px solid var(--accent);
  outline-offset: 2px;
}
#preview-root .pdf-page-preview-badge {
  background: var(--card);
  border: 1px solid var(--panel-border);
  border-radius: 999px;
  bottom: 0.55rem;
  color: var(--muted);
  font: 600 0.68em/1 system-ui, sans-serif;
  padding: 0.32rem 0.45rem;
  pointer-events: none;
  position: absolute;
  right: 0.55rem;
}
#preview-root math[display="block"] {
  display: block;
  margin: 1em 0;
  overflow-x: auto;
  overflow-y: hidden;
}
#preview-root mjx-container[display="true"] {
  display: block;
  margin: 1em 0;
  overflow-x: auto;
  overflow-y: hidden;
}
#preview-root .mermaid-container {
  text-align: center;
  margin: 1em 0;
  overflow-x: auto;
}
#preview-root .mermaid-container svg {
  max-width: 100%;
  height: auto;
}
</style>
</head>
<body>
  <article id="preview-root" data-wrap-code="${codeWrapping.wrapCode === true}">${preparedFragmentHtml}</article>
  <script>
${annotationHelpersScript}
  </script>
  <script>
${pdfFigureHelpersScript}
  </script>
  <script>
${codeWrapControlsScript}
  </script>
  <script type="module">
  (async () => {
    const annotationHelpers = window.PiMarkdownPreviewAnnotationHelpers || null;
    const pdfFigureHelpers = window.PiMarkdownPreviewPdfFigures || null;
    const previewAnnotationPlaceholders = ${annotationPlaceholdersJson};
    const previewInlinePdfData = ${inlinePdfDataJson};
    const previewPdfFigureRenderingEnabled = ${JSON.stringify(pdfFigureRenderingEnabled)};
    const DIFF_META_LINE_REGEX = /^(diff --git |index |new file mode |deleted file mode |similarity index |rename from |rename to |Binary files )/;

    const escapeRegExp = (text) => {
      const backslash = String.fromCharCode(92);
      const specials = '.+*?^' + '$' + '{}|[]' + backslash;
      return Array.from(String(text || '')).map((ch) => specials.includes(ch) ? backslash + ch : ch).join('');
    };

    const setAnnotationMarkerContent = (marker, text) => {
      if (!(marker instanceof HTMLElement)) return;
      const rendered = annotationHelpers && typeof annotationHelpers.renderPreviewAnnotationHtml === 'function'
        ? annotationHelpers.renderPreviewAnnotationHtml(text)
        : String(text || '');
      marker.innerHTML = rendered;
    };

    const replaceAnnotationTextNode = (textNode) => {
      if (!annotationHelpers || typeof annotationHelpers.collectInlineAnnotationMarkers !== 'function') return;
      const text = typeof textNode.nodeValue === 'string' ? textNode.nodeValue : '';
      if (!text || text.toLowerCase().indexOf('[an:') === -1) return;

      const markers = annotationHelpers.collectInlineAnnotationMarkers(text);
      if (!Array.isArray(markers) || markers.length === 0) return;

      const fragment = document.createDocumentFragment();
      let lastIndex = 0;
      markers.forEach((markerInfo) => {
        const token = markerInfo && typeof markerInfo.raw === 'string' ? markerInfo.raw : '';
        const start = markerInfo && typeof markerInfo.start === 'number' ? markerInfo.start : lastIndex;
        const end = markerInfo && typeof markerInfo.end === 'number' ? markerInfo.end : start;
        if (start > lastIndex) {
          fragment.appendChild(document.createTextNode(text.slice(lastIndex, start)));
        }

        const markerText = annotationHelpers && typeof annotationHelpers.normalizePreviewAnnotationLabel === 'function'
          ? annotationHelpers.normalizePreviewAnnotationLabel(markerInfo.body)
          : String(markerInfo && markerInfo.body || '').trim();
        if (markerText) {
          const markerEl = document.createElement('span');
          markerEl.className = 'annotation-marker';
          markerEl.title = token || markerText;
          setAnnotationMarkerContent(markerEl, markerText);
          fragment.appendChild(markerEl);
        }

        lastIndex = end;
      });

      if (lastIndex < text.length) {
        fragment.appendChild(document.createTextNode(text.slice(lastIndex)));
      }

      if (textNode.parentNode) {
        textNode.parentNode.replaceChild(fragment, textNode);
      }
    };

    const applyPreviewAnnotationPlaceholders = (root) => {
      if (!root || !Array.isArray(previewAnnotationPlaceholders) || previewAnnotationPlaceholders.length === 0) return;
      const placeholderMap = new Map();
      const placeholderTokens = [];
      previewAnnotationPlaceholders.forEach((entry) => {
        const token = entry && typeof entry.token === 'string' ? entry.token : '';
        if (!token) return;
        placeholderMap.set(token, entry);
        placeholderTokens.push(token);
      });
      if (placeholderTokens.length === 0) return;

      const placeholderPattern = new RegExp(placeholderTokens.map(escapeRegExp).join('|'), 'g');
      const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
      const textNodes = [];
      let node = walker.nextNode();
      while (node) {
        const textNode = node;
        const value = typeof textNode.nodeValue === 'string' ? textNode.nodeValue : '';
        if (value && value.indexOf('${PREVIEW_ANNOTATION_PLACEHOLDER_PREFIX}') !== -1) {
          const parent = textNode.parentElement;
          const tag = parent && parent.tagName ? parent.tagName.toUpperCase() : '';
          if (tag !== 'CODE' && tag !== 'PRE' && tag !== 'SCRIPT' && tag !== 'STYLE' && tag !== 'TEXTAREA') {
            textNodes.push(textNode);
          }
        }
        node = walker.nextNode();
      }

      textNodes.forEach((textNode) => {
        const text = typeof textNode.nodeValue === 'string' ? textNode.nodeValue : '';
        if (!text) return;
        placeholderPattern.lastIndex = 0;
        if (!placeholderPattern.test(text)) return;
        placeholderPattern.lastIndex = 0;

        const fragment = document.createDocumentFragment();
        let lastIndex = 0;
        let match;
        while ((match = placeholderPattern.exec(text)) !== null) {
          const token = match[0] || '';
          const entry = placeholderMap.get(token);
          const start = typeof match.index === 'number' ? match.index : 0;
          if (start > lastIndex) {
            fragment.appendChild(document.createTextNode(text.slice(lastIndex, start)));
          }
          if (entry) {
            const markerEl = document.createElement('span');
            markerEl.className = 'annotation-marker';
            const markerText = typeof entry.text === 'string' ? entry.text : token;
            markerEl.title = typeof entry.title === 'string' ? entry.title : markerText;
            setAnnotationMarkerContent(markerEl, markerText);
            fragment.appendChild(markerEl);
          } else {
            fragment.appendChild(document.createTextNode(token));
          }
          lastIndex = start + token.length;
          if (token.length === 0) {
            placeholderPattern.lastIndex += 1;
          }
        }

        if (lastIndex < text.length) {
          fragment.appendChild(document.createTextNode(text.slice(lastIndex)));
        }

        if (textNode.parentNode) {
          textNode.parentNode.replaceChild(fragment, textNode);
        }
      });
    };

    const decorateDiffCodeBlocks = (root) => {
      if (!root) return;
      const diffBlocks = Array.from(root.querySelectorAll('pre.sourceCode.diff code'));

      diffBlocks.forEach((codeBlock) => {
        const lineElements = Array.from(codeBlock.children).filter((child) => child instanceof HTMLElement);
        lineElements.forEach((lineEl) => {
          const text = typeof lineEl.textContent === 'string' ? lineEl.textContent : '';
          if (!text) return;

          if (/^\\+(?!\\+\\+)/.test(text)) {
            lineEl.classList.add('diff-line', 'diff-add-line');
          } else if (/^-(?!--)/.test(text)) {
            lineEl.classList.add('diff-line', 'diff-del-line');
          } else if (/^@@/.test(text)) {
            lineEl.classList.add('diff-line', 'diff-hunk-line');
          } else if (/^(?:\\+\\+\\+ |--- )/.test(text)) {
            lineEl.classList.add('diff-line', 'diff-header-line');
          } else if (DIFF_META_LINE_REGEX.test(text)) {
            lineEl.classList.add('diff-line', 'diff-meta-line');
          }

          const walker = document.createTreeWalker(lineEl, NodeFilter.SHOW_TEXT);
          const matches = [];
          let node = walker.nextNode();
          while (node) {
            const textNode = node;
            const value = typeof textNode.nodeValue === 'string' ? textNode.nodeValue : '';
            const parent = textNode.parentElement;
            if (value && value.toLowerCase().indexOf('[an:') !== -1 && parent && !parent.closest('a, .annotation-marker')) {
              matches.push(textNode);
            }
            node = walker.nextNode();
          }

          matches.forEach(replaceAnnotationTextNode);
        });
      });
    };

    const MATHJAX_CDN_URL = 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js';

    const waitForFonts = async () => {
      if ('fonts' in document) {
        try {
          await document.fonts.ready;
        } catch {}
      }
    };

    const waitForPaint = async () => {
      await new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve)));
    };

    const extractMathFallbackTex = (text, displayMode) => {
      const source = typeof text === 'string' ? text.trim() : '';
      if (!source) return '';

      if (displayMode) {
        if (source.startsWith('$$') && source.endsWith('$$') && source.length >= 4) {
          return source.slice(2, -2).trim();
        }
        if (source.startsWith('\\\\[') && source.endsWith('\\\\]') && source.length >= 4) {
          return source.slice(2, -2).trim();
        }
        return source;
      }

      if (source.startsWith('\\\\(') && source.endsWith('\\\\)') && source.length >= 4) {
        return source.slice(2, -2).trim();
      }
      if (source.startsWith('$') && source.endsWith('$') && source.length >= 2) {
        return source.slice(1, -1).trim();
      }
      return source;
    };

    const collectMathFallbackTargets = (root) => {
      if (!root) return [];
      const nodes = Array.from(root.querySelectorAll('.math.display, .math.inline'));
      const targets = [];
      const seenTargets = new Set();

      nodes.forEach((node) => {
        const displayMode = node.classList.contains('display');
        const rawText = typeof node.textContent === 'string' ? node.textContent : '';
        const tex = extractMathFallbackTex(rawText, displayMode);
        if (!tex) return;

        let renderTarget = node;
        if (displayMode) {
          const parent = node.parentElement;
          const parentText = parent && typeof parent.textContent === 'string' ? parent.textContent.trim() : '';
          if (parent && parent.tagName === 'P' && parentText === rawText.trim()) {
            renderTarget = parent;
          }
        }

        if (seenTargets.has(renderTarget)) return;
        seenTargets.add(renderTarget);
        targets.push({ renderTarget, displayMode, tex });
      });

      return targets;
    };

    let mathJaxPromise = null;
    const ensureMathJax = () => {
      if (window.MathJax && typeof window.MathJax.typesetPromise === 'function') {
        return Promise.resolve(window.MathJax);
      }
      if (mathJaxPromise) return mathJaxPromise;

      mathJaxPromise = new Promise((resolve, reject) => {
        window.MathJax = {
          loader: { load: ['[tex]/ams', '[tex]/noerrors', '[tex]/noundefined'] },
          tex: {
            inlineMath: [['\\\\(', '\\\\)'], ['$', '$']],
            displayMath: [['\\\\[', '\\\\]'], ['$$', '$$']],
            packages: { '[+]': ['ams', 'noerrors', 'noundefined'] },
          },
          options: {
            skipHtmlTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code'],
          },
          startup: { typeset: false },
        };

        const script = document.createElement('script');
        script.src = MATHJAX_CDN_URL;
        script.async = true;
        script.onload = () => {
          const api = window.MathJax;
          if (api && api.startup && api.startup.promise && typeof api.startup.promise.then === 'function') {
            api.startup.promise.then(() => resolve(api)).catch(reject);
            return;
          }
          if (api && typeof api.typesetPromise === 'function') {
            resolve(api);
            return;
          }
          reject(new Error('MathJax did not initialize.'));
        };
        script.onerror = () => reject(new Error('Failed to load MathJax.'));
        document.head.appendChild(script);
      }).catch((error) => {
        mathJaxPromise = null;
        throw error;
      });

      return mathJaxPromise;
    };

    const markerNeedsMath = (text) => {
      const source = typeof text === 'string' ? text : '';
      if (!source) return false;
      const backslash = String.fromCharCode(92);
      if (source.includes(backslash + '(') || source.includes(backslash + '[') || source.includes('$$')) return true;
      for (let index = 0; index < source.length - 1; index += 1) {
        const char = source[index];
        const next = source[index + 1] || '';
        if (char === '$' && next.trim() !== '') return true;
        if (char === backslash && /[A-Za-z]/.test(next)) return true;
      }
      return false;
    };

    const renderAnnotationMarkerMath = async (root) => {
      if (!root) return;
      const markers = Array.from(root.querySelectorAll('.annotation-marker')).filter((marker) => {
        if (!(marker instanceof HTMLElement)) return false;
        if (marker.querySelector('math, mjx-container')) return false;
        const text = typeof marker.textContent === 'string' ? marker.textContent : '';
        return markerNeedsMath(text);
      });
      if (markers.length === 0) return;

      let mathJax;
      try {
        mathJax = await ensureMathJax();
      } catch (e) {
        console.error('MathJax load failed:', e);
        return;
      }

      try {
        await mathJax.typesetPromise(markers);
      } catch (e) {
        console.error('Annotation math render failed:', e);
      }
    };

    const renderMathFallback = async (root) => {
      const fallbackTargets = collectMathFallbackTargets(root);
      if (fallbackTargets.length === 0) return;

      let mathJax;
      try {
        mathJax = await ensureMathJax();
      } catch (e) {
        console.error('MathJax load failed:', e);
        return;
      }

      fallbackTargets.forEach(({ renderTarget, displayMode, tex }) => {
        renderTarget.textContent = displayMode ? '\\\\[\\n' + tex + '\\n\\\\]' : '\\\\(' + tex + '\\\\)';
      });

      try {
        await mathJax.typesetPromise(fallbackTargets.map(({ renderTarget }) => renderTarget));
      } catch (e) {
        console.error('MathJax render failed:', e);
      }
    };

    let pdfJsPromise = null;
    const loadPdfJs = () => {
      if (pdfJsPromise) return pdfJsPromise;
      pdfJsPromise = import(${JSON.stringify(PDFJS_BROWSER_MODULE_URL)}).then((pdfjs) => {
        if (pdfjs.GlobalWorkerOptions) {
          pdfjs.GlobalWorkerOptions.workerSrc = ${JSON.stringify(PDFJS_BROWSER_WORKER_URL)};
        }
        return pdfjs;
      }).catch((error) => {
        pdfJsPromise = null;
        throw error;
      });
      return pdfJsPromise;
    };

    const renderPdfFigures = async (root) => {
      if (!previewPdfFigureRenderingEnabled) {
        window.__pdfFigureRenderResult = { status: 'skipped', total: 0, rendered: 0, multiPage: 0, failed: 0 };
        return;
      }
      if (!pdfFigureHelpers || typeof pdfFigureHelpers.renderSinglePagePdfFigures !== 'function') {
        window.__pdfFigureRenderResult = { status: 'unavailable', total: 0, rendered: 0, multiPage: 0, failed: 0 };
        return;
      }
      window.__pdfFigureRenderResult = { status: 'pending' };
      try {
        window.__pdfFigureRenderResult = await pdfFigureHelpers.renderSinglePagePdfFigures(root, {
          documentOptions: ${JSON.stringify(PDFJS_BROWSER_DOCUMENT_OPTIONS)},
          inlinePdfData: previewInlinePdfData,
          loadPdfJs,
        });
      } catch (error) {
        window.__pdfFigureRenderResult = { status: 'failed', error: error instanceof Error ? error.message : String(error) };
        console.warn('PDF figure rendering failed; retaining native PDF embeds.', error);
      }
    };

${buildMermaidBrowserModule(mermaidConfigJson, mermaidIconPacksJson)}

    const root = document.getElementById('preview-root');
    try {
      await renderMermaid();
      applyPreviewAnnotationPlaceholders(root);
      decorateDiffCodeBlocks(root);
      await renderAnnotationMarkerMath(root);
      await renderMathFallback(root);
      await renderPdfFigures(root);
      if (${codeWrapping.controls !== false}) {
        window.PiMarkdownPreviewCodeWrap?.installCodeWrapControls(root);
      }
      await waitForFonts();
      await waitForPaint();
    } finally {
      window.__mermaidDone = true;
      window.dispatchEvent(new Event('pi-markdown-preview-ready'));
    }
  })();
  </script>
</body>
</html>`;
}

async function renderPreviewHtmlDocument(
	markdown: string,
	style: PreviewStyle,
	resourcePath?: string,
	isLatex?: boolean,
	fontSizePx?: number,
	signal?: AbortSignal,
	inlineLocalPdfData = false,
): Promise<{ html: string; normalizedMarkdown: string; fontSizePx: number }> {
	const previewFontSizePx = normalizePreviewFontSizePx(fontSizePx, DEFAULT_BROWSER_PREVIEW_FONT_SIZE_PX);
	const { normalizedMarkdown, pandocMarkdown, annotationPlaceholders } = prepareBrowserPreviewMarkdown(markdown, isLatex);
	const fragmentHtml = markPandocPdfEmbeds(await renderMarkdownToHtmlWithPandoc(pandocMarkdown, resourcePath, isLatex, signal));
	const inlinePdfData = inlineLocalPdfData
		? await collectInlineLocalPdfData(fragmentHtml, resourcePath, signal)
		: {};
	return {
		html: buildBrowserHtmlFromPandocFragment(fragmentHtml, style, resourcePath, annotationPlaceholders, previewFontSizePx, inlinePdfData, true),
		normalizedMarkdown,
		fontSizePx: previewFontSizePx,
	};
}

export { renderPreviewHtmlDocument, getPreviewStyle, buildBrowserHtmlFromPandocFragment, prepareFilePreview, normalizePreviewFontSizePx, DEFAULT_BROWSER_PREVIEW_FONT_SIZE_PX, RENDER_VERSION, DARK_PREVIEW_PALETTE, LIGHT_PREVIEW_PALETTE, extractAssistantMarkdownContent };
export type { PreviewStyle, ThemeMode, PreviewPalette, PreparedFilePreview };
